package br.com.sge.modules.notificacoes.entity;

public enum TipoNotificacao {
    COBRANCA_GERADA,
    PAGAMENTO_CONFIRMADO,
    COBRANCA_VENCIDA,
    NOTA_LANCADA,
    FALTA_REGISTRADA,
    COMUNICADO_NOVO,
    AGENDAMENTO_SAUDE,
    REMATRICULA_ENVIADA,
    OCORRENCIA_REGISTRADA,
    MATRICULA_NOVA_ENVIADA,
    COLEGIADO_REUNIAO,
    COLEGIADO_ENCAMINHAMENTO,
    GALERIA_NOVA
}
